<?php

function dna_menu() {
    $items['dna'] = array(
        'title' => 'DNA Helix Generator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['dna_success'] = array(
        'title' => 'success',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function dna_form() {
    $form['input'] = array(
        '#title' => 'Enter one half of your DNA helix',
        '#type' => 'textfield',
        // '#element_validate' => array('element_validate_dna'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Make DNA Work',
    );

    return $form;
}

// function element_validate_dna($element) {
//     $valid_input = array('A', 'T', 'C', 'G');
//     if (!(in_array(strtoupper($element['#value']), $valid_input))) {
//         form_error($element, t("Please only enter a valid element ('A', 'T', 'C', 'G')"));
//     }
// }

function make_dna_work($input) {
    $input_uppercase = strtoupper($input);
    $input_exploded = explode(' ', $input_uppercase);
    $new_DNA = '';
    $output_DNA = [];
    foreach ($input_exploded as $DNA) {
        if ($DNA === 'A') {
            $new_DNA === 'T';
            array_push($output_DNA, $new_DNA);
        } elseif ($DNA === 'T') {
            $new_DNA === 'A';
            array_push($output_DNA, $new_DNA);
        } elseif ($DNA === 'C') {
            $new_DNA === 'G';
            array_push($output_DNA, $new_DNA);
        } elseif ($DNA === 'G') {
            $new_DNA === 'C';
            array_push($output_DNA, $new_DNA);
        }
    }

    return implode(' ', $output_DNA);
}

function dna_form_submit($form, &$form_state) {
    $input = $form_state['values']['input'];
    $result = make_dna_work($input);
    $_SESSION['input'] = $input;
    $_SESSION['result'] = $result;

    $form_state['redirect'] = 'dna_success';
}

function dna_success() {
    $input = $_SESSION['input'];
    $result = $_SESSION['result'];
    return '<p>You entered: ' . $input . '. The other half of your DNA is ' . $result . '</p>';
}

// if (!($index == 'A') || ($index == 'T') ||( $index == 'C') || ($index == 'G')) {
//     return
// }
