<?php

function dna_menu() {
    $items['dna'] = array(
        'title' => 'DNA Helix Generator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['dna_success'] = array(
        'title' => 'success',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}
